// https://en.wikipedia.org/wiki/ListofJavabytecode_instructions
use super::types::*;
#[derive(Debug)]
pub struct Instruction(pub U4, pub Operation); //U2 = address

#[derive(Debug, Clone)]
pub enum Operation {
    Aaload,
    Aastore,
    Aconstnull,
    Aload(u8),
    Aload0,
    Aload1,
    Aload2,
    Aload3,
    Anewarray(u8, u8),
    Areturn,
    Arraylength,
    Astore(u8),
    Astore0,
    Astore1,
    Astore2,
    Astore3,
    Athrow,
    Baload,
    Bastore,
    Bipush(u8),
    Breakpoint,
    Caload,
    Castore,
    Checkcast(u8, u8),
    D2f,
    D2i,
    D2l,
    Dadd,
    Daload,
    Dastore,
    Dcmpg,
    Dcmpl,
    Dconst0,
    Dconst1,
    Ddiv,
    Dload(u8),
    Dload0,
    Dload1,
    Dload2,
    Dload3,
    Dmul,
    Dneg,
    Drem,
    Dreturn,
    Dstore(u8),
    Dstore0,
    Dstore1,
    Dstore2,
    Dstore3,
    Dsub,
    Dup,
    Dupx1(u8, u8),
    Dupx2(u8, u8, u8),
    Dup2,
    Dup2x1(u8, u8, u8),
    Dup2x2,
    F2d,
    F2i,
    F2l,
    Fadd,
    Faload,
    Fastore,
    Fcmpg,
    Fcmpl,
    Fconst0,
    Fconst1,
    Fconst2,
    Fdiv,
    Fload(u8),
    Fload0,
    Fload1,
    Fload2,
    Fload3,
    Fmul,
    Fneg,
    Frem,
    Freturn,
    Fstore(u8),
    Fstore0,
    Fstore1,
    Fstore2,
    Fstore3,
    Fsub,
    Getfield(u8, u8),
    Getstatic(u8, u8),
    Goto(u8, u8),
    Gotow(u8, u8, u8, u8),
    I2b,
    I2c,
    I2d,
    I2f,
    I2l,
    I2s,
    Iadd,
    Iaload,
    Iand,
    Iastore,
    Iconstm1,
    Iconst0,
    Iconst1,
    Iconst2,
    Iconst3,
    Iconst4,
    Iconst5,
    Idiv,
    Ifacmpeq(u8, u8), //u16
    Ifacmpne(u8, u8),
    Ificmpeq(u8, u8),
    Ificmpge(u8, u8),
    Ificmpgt(u8, u8),
    Ificmple(u8, u8),
    Ificmplt(u8, u8),
    Ificmpne(u8, u8),
    Ifeq(u8, u8),
    Ifge(u8, u8),
    Ifgt(u8, u8),
    Ifle(u8, u8),
    Iflt(u8, u8),
    Ifne(u8, u8),
    Ifnonnull(u8, u8),
    Ifnull(u8, u8),
    Iinc(u8, u8),
    Iload(u8),
    Iload0,
    Iload1,
    Iload2,
    Iload3,
    Impdep1,
    Impdep2,
    Imul,
    Ineg,
    Instanceof(u8, u8),
    Invokedynamic(u8, u8, u8, u8),
    Invokeinterface(u8, u8, u8, u8),
    Invokespecial(u8, u8),
    Invokestatic(u8, u8),
    Invokevirtual(u8, u8),
    Ior,
    Irem,
    Ireturn,
    Ishl,
    Ishr,
    Istore(u8),
    Istore0,
    Istore1,
    Istore2,
    Istore3,
    Isub,
    Iushr,
    Ixor,
    Jsr(u8, u8),
    Jsrw(u8, u8, u8, u8),
    L2d,
    L2f,
    L2i,
    Ladd,
    Laload,
    Land,
    Lastore,
    Lcmp,
    Lconst0,
    Lconst1,
    Ldc(u8),
    Ldcw(u8, u8),
    Ldc2w(u8, u8),
    Ldiv,
    Lload(u8),
    Lload0,
    Lload1,
    Lload2,
    Lload3,
    Lmul,
    Lneg,
    Lookupswitch(Vec<u8>), //8
    Lor,
    Lrem,
    Lreturn,
    Lshl,
    Lshr,
    Lstore(u8),
    Lstore0,
    Lstore1,
    Lstore2,
    Lstore3,
    Lsub,
    Lushr,
    Lxor,
    Monitorenter,
    Monitorexit,
    Multianewarray(u8, u8, u8),
    New(u8, u8),
    Newarray(u8),
    Nop,
    Pop,
    Pop2,
    Putfield(u8, u8),
    Putstatic(u8, u8),
    Ret(u8),
    Return,
    Saload,
    Sastore,
    Sipush(u8, u8),
    Swap(u8, u8),
    Tableswitch(Vec<u8>), //16
    Wide(u8, u8, u8),
}
